### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by devstefancho** [devstefancho/country-data-listing#2]
* Fix bug
     - [x] not to delete the same occurrences at the same time in TableChild.js
         - not to submit duplicate
     - [x] submit change Character Case automatically (ie. country first char will be Upper)
     - [x] clear form after submit
     - [x] sort bug in calling code column (current sort is done by string, so change to number) in SortButton.js
     - [x] validation for form (ie country form is only accept english letters)
     - [x] disable submit If not valid
     - [] disable submit while submitting
     - [x] proptypes console warning

    * Refactoring
     - [] invalid message variable group

    * User Friendly (UI)
     - [] make error message of form for more visible
     - [] table resizing stablity
     - [] hover mouse motion on trash icon
     - [x] highlight form

    * Add performance
     - [x] cross browsing
     - [x] denounce or throttle search bar
     - [] unit test 
 
    * Practice deep in Redux-Form
    * Re structuring component
